IvarK/IvarK.github.io

index.html, javascripts/game.js, javascripts/util.js
Created a util.js file to contain saving, and loading utilities for now. May refactor more in the future.
=> Refactoring update

javascripts/game.js
-Sci and engineering dont have the same values.
-Dimension numbers have decimals now, as well as other things such as their power.
=> Fix for various bugs.

javascripts/game.js
And cleaned the formatting of the code a little.
=> Added support for custom Notation in achieve tooltips

index.html, javascripts/game.js
=> Achievements (html part)

changelog.html, javascripts/game.js
am still totally confused by how github
=> Achievements (js part)

index.html, javascripts/game.js
Reverts IvarK/IvarK.github.io#45
=> Revert "Tmpe"

javascripts/game.js
=> challenge3

javascripts/game.js
Reduced duplicate code in achievement handling.
=> fixed a bug that may cause players to miss achievements when using Buy Max

javascripts/game.js
=> Fixed displayTime

index.html, javascripts/game.js
Should sacrifices be modified to affect 6th dim? not sure
=> Challenge 4

javascripts/game.js
=> forgot a few things for challenge 4

javascripts/game.js
it was possible to get it to 100.07%
=> percentage to infinity fix

javascripts/game.js
=> small chall4 fixes

index.html, javascripts/game.js
=> tickspeed challenge

index.html, javascripts/game.js
8.Everything gets downgraded (1st gives half, 2nd gives antimatter, 3rd gives first etc.)
1st works a bit weirdly but i did it for a reason (note: not a very good reason)
=> a challenge

index.html, javascripts/game.js
=> Another Challenge

javascripts/game.js
=> savefile size reduction

index.html, javascripts/game.js
theres probably more stuff to do before merging (416-420, and probably also adding some more in that area too)
=> infinity upgrades

javascripts/game.js
i'm not doing the rest you do it (yes i know you have to cache the ETAs and not show them directly but idk man)
=> ETA part 1

javascripts/game.js
+3 things and it changes at 1 instead of 5 and protons appear at 0.1 instead of 2
=> scale update

index.html, javascripts/game.js
=> achievement rewards

index.html, javascripts/game.js, stylesheets/theme-Dark.css
I added some basic support for themes, along with a simple dark theme I made.
=> Added support for themes

index.html, javascripts/game.js, stylesheets/styles.css, stylesheets/theme-Dark.css
I fixed those problems you mentioned and just made it look better.
=> Added support for themes, but better this time

javascripts/game.js
gain IP passively offline based on your highest IP/min in a passive infinity, but only when break is off.
=> offline IP boost

javascripts/game.js, stylesheets/theme-Dark.css
Made the text on both of the 2 buttons on the bottom of this picture red and the border blue. They were both the same class in the HTML but a line in the JS was overwriting the class of one of them.
=> Fixed tickspeed cost and dim cost upgrades not having the same style, and improved dark theme

stylesheets/theme-Dark.css
https://my.mixtape.moe/dtceio.mp4
I didn't want to mess with the main theme just in case you didn't like it, so I only put them in the dark theme. It's easy enough to copy the code if you want to add them in.
=> Added animation for time studies in dark theme, and improved dark theme

stylesheets/styles.css, stylesheets/theme-Dark.css
I think the dark theme is complete at this point. I've spent hours thinking about improvements and I just come up flat now.
=> Removed extra whitespace from styles, and improved dark theme.

javascripts/game.js, stylesheets/styles.css, stylesheets/theme-Christmas.css
fixed a typo with time study 102 that broke the game
made the font on the buy time theorem buttons bigger
improved christmas theme
simplified the check for "The 9th Dimension is a lie" achievement
made eternity button only show after you have all 8 inf dims (doesn't really effect normal play, only edge cases)
fix progressbar tooltip
=> Fixes and improvements

javascripts/game.js, stylesheets/styles.css, stylesheets/theme-Finnish.css
fixed newdimlocked showing a pointer when you hovered on it
fixed achievement colors in the 6/12 theme
improved display of EP costs for time studies
fixed last ten eternities stat screen saying IP instead of EP
made ctrl+hotkey not work, in turn making ctrl+c not big crunch
=> Fixes and improvements part 2

stylesheets/theme-Finnish.css
made a small change to make the dimensions text more readable
=> Finnish that one thing

index.html, javascripts/game.js, stylesheets/styles.css, stylesheets/theme-Dark.css, stylesheets/theme-Metro.css, stylesheets/theme-S1.css
higher bottom padding for cloud save popup
CSS for cloud save popup in dark, metro, and S1 themes
center EP mult button
make challenges 1-12 start as completed if you have the 2 eternity milestone
=> Fixes and improvements 3

index.html, stylesheets/styles.css
added 3px margin-top to replicanti autobuyer buttons 
fixed the hidden centering divs next to ep mult being hoverable
fixed the study tree being slightly off center in kong
=> Fixes and a change

javascripts/game.js
the one where you had to get a 1.79e308 sacrifice in postc2 after sacrificing for more than 1
someone in the discord got it, and apparently it was still there, so I removed it
also, fixed eternitied stat submission breaking stuff sometimes
=> Fix old achievement 97 code still being there

stylesheets/theme-Dark Metro.css, stylesheets/theme-Metro.css
=> Minor theme touch-up

javascripts/game.js
I made this before that edit just had to get home so I could post it. I didn't notice there had been changes.
=> Autobuyer Limit Fix

javascripts/game.js, stylesheets/styles.css
setting stuff up is always a pain, so its good to test sometimes
=> slab's misc stuff

javascripts/game.js
fix secretThemeKey wasting save space
fix repli galaxy autobuyer display not updating in certain cases
fix inf dim autobuyers working in EC2
=> Minor fixes

index.html, javascripts/game.js
as seconded in the suggestion channel on discord, a slight organization on the general statistics tab by separating Eternities, Infinities, and general statistics. Also shows challenge time sums to allow players to not have to check on a calculator
=> Statistics Page QOL updates

howto.html, index.html, javascripts/game.js
"Long lasting relationship" goal increased from 30 seconds to 60
fixed eternity upgradess 4-6 not respecting notation
reduced the cost of eternity upgrade 4 from 1e18 to 1e16
made the offlineprod breaking infinity upgrade use the infinimultbtn class
disabled ID autobuyers in EC10
clarified that yo dawg requires IP not AM
clarified wording for TT costs in the how to
prevent awarding 8 nobody got time through forced eternities
add colons before challenge record listings
changed "if you would write" to > "if you wrote" under statistics
made the eternity point multiplier update when changing notation
made the replicanti galaxy description have proper plurals
=> Fixes and improvements 4.

javascripts/game.js
this is a simple fix for basically all the problems with challenges being weird, I think
=> Cap antimatter production if over challenge target to prevent infinite AM exploits.

javascripts/game.js
Put the if in the right place :stuck_out_tongue:
=> Fix Brackets

javascripts/game.js
using my improved knowledge of JS I have slightly improved some functionality
=> remove control down, disable hotkeys while using text inputs

javascripts/game.js
made study 233 visually update the max RG price
added control down back because you still wouldn't want to crunch when copying text from the game
added a missing " EP/min" text to the end of peak EP/min
=> little fixes

index.html, javascripts/game.js
fixed a bug where replicanti amount would reduce if your interval was over 50 with timestudy 192
updated r123 to account for the existence of EC11 and 12
=>  fix over inf replicanti breaking above 50ms interval 568d4c4, update r123

index.html, javascripts/game.js
added an option to hold shift to show study numbers above each time study
=> hold shift to show study numbers

javascripts/game.js
Fixes the issues described in issue #231.
Infinity Challenge 2 starts with resets so we also take account of resets when starting a challenge.
=> Fixed dimension multipliers, both after galaxy and crunch and with respect to "One for each dimension"

index.html, javascripts/core/achievements.js, javascripts/core/kong.js, javascripts/game.js
So, I've touched kong and stuff, so you might want to check if we can still pay you monies for kreds.
I've checked that there were no leaks for, like, five minutes or so. I'll leave it for overnight to be sure, but I doubt that there will be more of them.
Also, console errors are eliminated as well.
1. All Kong stuff was extracted to kong.js and wrapped in kong object
2. Kong and PlayFab will not be called unless we are hosted inside Kongregate IFrame (document.referrer checks for that)
Resolves: #243
=> Fix Kongregate integration

javascripts/core/dimboost.js, javascripts/core/load_functions.js, javascripts/game.js, version.txt
Should work, tested a bit but not that much.
=> Remove shame

javascripts/game.js
uppercase words look weird in this sentence
=> fixed spelling
